// 샵 테이블(sh_shop_*)을 기존 Supabase(뭄바이) → 새 Supabase(서울)로 이전
// 사용법: node scripts/migrate-shop-db.mjs schema   (구조 생성: 확장·시퀀스·테이블·제약·인덱스·RLS·함수)
//         node scripts/migrate-shop-db.mjs data     (데이터 전체 복사 — 새 DB 의 기존 행은 비우고 다시 채움)
//         node scripts/migrate-shop-db.mjs verify   (행 수 대조)
import fs from 'node:fs'

const env = Object.fromEntries(
  fs.readFileSync('.env.local', 'utf8').split(/\r?\n/).map(l => l.match(/^([A-Z0-9_]+)=(.*)$/)).filter(Boolean).map(m => [m[1], m[2]]),
)
const OLD = 'jzrdajrymxxwmeizxyck'
const NEW = process.env.SHOP_NEW_REF || 'uehluxtuaotnezfnobhj'

async function sql(ref, query) {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${env.SUPABASE_ACCESS_TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  })
  const text = await res.text()
  if (!res.ok) throw new Error(`[${ref}] ${res.status} ${text}\n--- query ---\n${query.slice(0, 500)}`)
  return JSON.parse(text)
}

// FK 의존 순서
const TABLES = [
  'sh_shop_customers', 'sh_shop_products', 'sh_shop_reservations', 'sh_shop_reservation_history',
  'sh_shop_customer_history', 'sh_shop_payments', 'sh_shop_prepaid_ledger', 'sh_shop_closed_dates',
  'sh_shop_login_attempts', 'sh_shop_checklist_sessions', 'sh_shop_checklist', 'sh_shop_checklist_history',
  'sh_shop_floorplans', 'sh_shop_locations',
]
const q = s => `'${s.replace(/'/g, "''")}'`

async function schema() {
  const all = await sql(OLD, `select relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and relname like 'sh_shop_%'`)
  const missing = all.map(r => r.relname).filter(t => !TABLES.includes(t))
  if (missing.length) throw new Error('목록에 없는 샵 테이블: ' + missing.join(', '))

  const ddl = ['create extension if not exists btree_gist;', 'create extension if not exists pgcrypto;']

  const seqs = await sql(OLD, `select sequencename from pg_sequences where schemaname = 'public' and sequencename like 'sh_shop_%'
    and sequencename not in (select pg_get_serial_sequence(format('%I', c.relname), a.attname)::regclass::text
      from pg_attribute a join pg_class c on c.oid = a.attrelid where a.attidentity <> '' and c.relname like 'sh_shop_%')`)
  for (const s of seqs) ddl.push(`create sequence if not exists public.${s.sequencename};`)

  const cols = await sql(OLD, `select c.relname, a.attname, format_type(a.atttypid, a.atttypmod) t, a.attnotnull nn,
      pg_get_expr(d.adbin, d.adrelid) def, a.attidentity idn
    from pg_attribute a join pg_class c on c.oid = a.attrelid join pg_namespace n on n.oid = c.relnamespace
    left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    where n.nspname = 'public' and c.relkind = 'r' and c.relname like 'sh_shop_%' and a.attnum > 0 and not a.attisdropped
    order by c.relname, a.attnum`)
  for (const t of TABLES) {
    const lines = cols.filter(c => c.relname === t).map(c => {
      let l = `  "${c.attname}" ${c.t}`
      if (c.idn === 'a') l += ' generated always as identity'
      else if (c.idn === 'd') l += ' generated by default as identity'
      else if (c.def) l += ` default ${c.def}`
      if (c.nn) l += ' not null'
      return l
    })
    ddl.push(`create table if not exists public.${t} (\n${lines.join(',\n')}\n);`)
  }
  for (const s of seqs) {
    const owner = cols.find(c => c.def && c.def.includes(`'${s.sequencename}'`))
    if (owner) ddl.push(`alter sequence public.${s.sequencename} owned by public.${owner.relname}."${owner.attname}";`)
  }

  const cons = await sql(OLD, `select conrelid::regclass::text tbl, conname, contype, pg_get_constraintdef(oid) def
    from pg_constraint where conrelid::regclass::text like 'sh_shop_%' order by case contype when 'f' then 2 else 1 end, conname`)
  for (const c of cons) {
    ddl.push(`do $$ begin if not exists (select 1 from pg_constraint where conname = ${q(c.conname)}) then
      alter table public.${c.tbl} add constraint "${c.conname}" ${c.def}; end if; end $$;`)
  }

  const idx = await sql(OLD, `select indexdef from pg_indexes where schemaname = 'public' and tablename like 'sh_shop_%'
    and indexname not in (select conname from pg_constraint)`)
  for (const i of idx) ddl.push(i.indexdef.replace(/^CREATE (UNIQUE )?INDEX /, 'CREATE $1INDEX IF NOT EXISTS ') + ';')

  const rls = await sql(OLD, `select relname from pg_class where relname like 'sh_shop_%' and relkind = 'r' and relrowsecurity`)
  for (const r of rls) ddl.push(`alter table public.${r.relname} enable row level security;`)
  const pol = await sql(OLD, `select count(*)::int n from pg_policies where tablename like 'sh_shop_%'`)
  if (pol[0].n) throw new Error('정책(policy) 이전은 미지원 — 수동 확인 필요')

  const fns = await sql(OLD, `select pg_get_functiondef(p.oid) def, p.oid::regprocedure::text sig
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and proname like 'sh_shop_%'`)
  for (const f of fns) {
    ddl.push(f.def + ';')
    ddl.push(`revoke all on function ${f.sig} from public, anon, authenticated;`)
    ddl.push(`grant execute on function ${f.sig} to service_role;`)
  }

  const script = ddl.join('\n\n')
  fs.writeFileSync('docs/sql/shop-db-seoul-schema.sql', script)
  await sql(NEW, script)
  console.log(`구조 생성 완료: 테이블 ${TABLES.length}, 시퀀스 ${seqs.length}, 제약 ${cons.length}, 인덱스 ${idx.length}, RLS ${rls.length}, 함수 ${fns.length}`)
}

async function data() {
  // 비우기(역순) 후 채우기(정순)
  await sql(NEW, `truncate ${[...TABLES].reverse().map(t => 'public.' + t).join(', ')} restart identity cascade;`)
  for (const t of TABLES) {
    const rows = await sql(OLD, `select coalesce(json_agg(x), '[]'::json) j from public.${t} x`)
    const json = JSON.stringify(rows[0].j)
    if (json === '[]') { console.log(`${t}: 0`); continue }
    if (json.includes('$shopjson$')) throw new Error('구분자 충돌')
    const identity = await sql(NEW, `select count(*)::int n from pg_attribute a join pg_class c on c.oid = a.attrelid
      where c.relname = ${q(t)} and a.attidentity = 'a'`)
    await sql(NEW, `insert into public.${t} ${identity[0].n ? 'overriding system value' : ''}
      select * from json_populate_recordset(null::public.${t}, $shopjson$${json}$shopjson$::json);`)
    console.log(`${t}: ${rows[0].j.length}`)
  }
  // 시퀀스/identity 를 최대값 이후로
  await sql(NEW, `do $$ declare r record; begin
    for r in select c.relname tbl, a.attname col, pg_get_serial_sequence(format('public.%I', c.relname), a.attname) seq
      from pg_attribute a join pg_class c on c.oid = a.attrelid join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relname like 'sh_shop_%' and a.attnum > 0
        and pg_get_serial_sequence(format('public.%I', c.relname), a.attname) is not null
    loop
      execute format('select setval(%L, coalesce((select max(%I) from public.%I), 0) + 1, false)', r.seq, r.col, r.tbl);
    end loop; end $$;`)
  console.log('시퀀스 재설정 완료')
}

async function verify() {
  let ok = true
  for (const t of TABLES) {
    const [a] = await sql(OLD, `select count(*)::int n, md5(coalesce(string_agg(x::text, '|' order by x::text), '')) h from public.${t} x`)
    const [b] = await sql(NEW, `select count(*)::int n, md5(coalesce(string_agg(x::text, '|' order by x::text), '')) h from public.${t} x`)
    const same = a.n === b.n && a.h === b.h
    if (!same) ok = false
    console.log(`${same ? 'OK  ' : 'DIFF'} ${t}: ${a.n} → ${b.n}`)
  }
  console.log(ok ? '\n전체 일치' : '\n불일치 있음')
  process.exit(ok ? 0 : 1)
}

const cmd = process.argv[2]
if (cmd === 'schema') await schema()
else if (cmd === 'data') await data()
else if (cmd === 'verify') await verify()
else console.log('schema | data | verify')
