// 지정한 테이블을 기존 공용 Supabase(뭄바이) → 서울 Supabase 로 이전 (대소문자 테이블명·RLS 정책 지원)
// 사용법: node scripts/migrate-tables.mjs <ledger> schema|data|verify
//   ledger: 가계부(cafe24/moneybook) 테이블 묶음
import fs from 'node:fs'

const env = Object.fromEntries(
  fs.readFileSync('.env.local', 'utf8').split(/\r?\n/).map(l => l.match(/^([A-Z0-9_]+)=(.*)$/)).filter(Boolean).map(m => [m[1], m[2]]),
)
const OLD = 'jzrdajrymxxwmeizxyck'
const NEW = 'uehluxtuaotnezfnobhj'

// FK 의존 순서(참조되는 쪽 먼저)
const SETS = {
  ledger: [
    'TB_AUTH', 'TB_BANK', 'TB_BANK_SUB', 'TB_WHERE', 'TB_WHAT', 'TB_WHO', 'TB_LIMIT', 'TB_CARD',
    'TB_RECURRING', 'TN_LIST',
    'EST_TB_BANK', 'EST_TB_BANK_SUB', 'EST_TB_WHERE', 'EST_TB_WHAT', 'EST_TB_LIMIT', 'EST_TN_LIST',
    'TB_LOCATION', 'MSG_LIST', 'TB_APP_FILTER', 'tb_notify_raw',
    'six_member', 'six_list', 'six_list_place', 'six_list_who',
  ],
}

async function sql(ref, query) {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${env.SUPABASE_ACCESS_TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  })
  const text = await res.text()
  if (!res.ok) throw new Error(`[${ref}] ${res.status} ${text}\n--- query ---\n${query.slice(0, 600)}`)
  return JSON.parse(text)
}

const lit = s => `'${String(s).replace(/'/g, "''")}'`
const id = s => `"${String(s).replace(/"/g, '""')}"`

const [setName, cmd] = process.argv.slice(2)
const TABLES = SETS[setName]
if (!TABLES) { console.log('세트: ' + Object.keys(SETS).join(', ')); process.exit(1) }
const inList = TABLES.map(lit).join(', ')
const oidList = `(select oid from pg_class where relnamespace = 'public'::regnamespace and relname in (${inList}))`

async function schema() {
  const exist = await sql(OLD, `select relname from pg_class where relnamespace = 'public'::regnamespace and relkind = 'r' and relname in (${inList})`)
  const missing = TABLES.filter(t => !exist.some(e => e.relname === t))
  if (missing.length) throw new Error('기존 DB 에 없는 테이블: ' + missing.join(', '))
  const clash = await sql(NEW, `select relname from pg_class where relnamespace = 'public'::regnamespace and relname in (${inList})`)
  if (clash.length) throw new Error('새 DB 에 이미 있는 테이블: ' + clash.map(c => c.relname).join(', '))

  const ddl = []
  // 기본값에 쓰이는 일반 시퀀스(identity 제외)
  const seqs = await sql(OLD, `select distinct s.relname seq, t.relname tbl, a.attname col
    from pg_depend d join pg_class s on s.oid = d.objid and s.relkind = 'S'
    join pg_class t on t.oid = d.refobjid join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
    where d.refobjid in ${oidList} and d.deptype = 'a'`)
  const defSeqs = await sql(OLD, `select distinct (regexp_match(pg_get_expr(d.adbin, d.adrelid), 'nextval\\(''(?:public\\.)?"?([^"'']+)"?''::regclass'))[1] seq
    from pg_attrdef d where d.adrelid in ${oidList} and pg_get_expr(d.adbin, d.adrelid) like 'nextval%'`)
  const allSeqs = [...new Set([...seqs.map(s => s.seq), ...defSeqs.map(s => s.seq).filter(Boolean)])]
  for (const s of allSeqs) ddl.push(`create sequence if not exists public.${id(s)};`)

  const cols = await sql(OLD, `select c.relname, a.attname, format_type(a.atttypid, a.atttypmod) t, a.attnotnull nn,
      pg_get_expr(d.adbin, d.adrelid) def, a.attidentity idn
    from pg_attribute a join pg_class c on c.oid = a.attrelid
    left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    where c.oid in ${oidList} and a.attnum > 0 and not a.attisdropped order by c.relname, a.attnum`)
  for (const t of TABLES) {
    const lines = cols.filter(c => c.relname === t).map(c => {
      let l = `  ${id(c.attname)} ${c.t}`
      if (c.idn === 'a') l += ' generated always as identity'
      else if (c.idn === 'd') l += ' generated by default as identity'
      else if (c.def) l += ` default ${c.def}`
      if (c.nn) l += ' not null'
      return l
    })
    ddl.push(`create table public.${id(t)} (\n${lines.join(',\n')}\n);`)
  }
  for (const s of seqs) ddl.push(`alter sequence public.${id(s.seq)} owned by public.${id(s.tbl)}.${id(s.col)};`)

  const cons = await sql(OLD, `select c.relname tbl, k.conname, pg_get_constraintdef(k.oid) def
    from pg_constraint k join pg_class c on c.oid = k.conrelid where k.conrelid in ${oidList}
    order by case k.contype when 'f' then 2 else 1 end, k.conname`)
  for (const c of cons) ddl.push(`alter table public.${id(c.tbl)} add constraint ${id(c.conname)} ${c.def};`)

  const idx = await sql(OLD, `select indexdef from pg_indexes where schemaname = 'public' and tablename in (${inList})
    and indexname not in (select conname from pg_constraint where conrelid in ${oidList})`)
  for (const i of idx) ddl.push(i.indexdef + ';')

  const rls = await sql(OLD, `select relname from pg_class where oid in ${oidList} and relrowsecurity`)
  for (const r of rls) ddl.push(`alter table public.${id(r.relname)} enable row level security;`)
  const pols = await sql(OLD, `select tablename, policyname, permissive, roles, cmd, qual, with_check from pg_policies
    where schemaname = 'public' and tablename in (${inList})`)
  for (const p of pols) {
    const roles = String(p.roles).replace(/[{}]/g, '').split(',').map(r => r === 'public' ? 'public' : id(r)).join(', ')
    ddl.push(`create policy ${id(p.policyname)} on public.${id(p.tablename)} as ${p.permissive.toLowerCase()} for ${p.cmd.toLowerCase()} to ${roles}`
      + (p.qual ? ` using (${p.qual})` : '') + (p.with_check ? ` with check (${p.with_check})` : '') + ';')
  }

  const script = ddl.join('\n\n')
  fs.writeFileSync(`docs/sql/${setName}-seoul-schema.sql`, script)
  await sql(NEW, script)
  console.log(`구조 생성: 테이블 ${TABLES.length}, 시퀀스 ${allSeqs.length}, 제약 ${cons.length}, 인덱스 ${idx.length}, RLS ${rls.length}, 정책 ${pols.length}`)
}

async function data() {
  await sql(NEW, `truncate ${[...TABLES].reverse().map(t => 'public.' + id(t)).join(', ')} restart identity cascade;`)
  const BATCH = 2000
  for (const t of TABLES) {
    const [{ n }] = await sql(OLD, `select count(*)::int n from public.${id(t)}`)
    const identity = await sql(NEW, `select count(*)::int n from pg_attribute where attrelid = 'public.${id(t)}'::regclass and attidentity = 'a'`)
    for (let off = 0; off < n; off += BATCH) {
      const rows = await sql(OLD, `select coalesce(json_agg(x), '[]'::json) j from (select * from public.${id(t)} order by ctid offset ${off} limit ${BATCH}) x`)
      const json = JSON.stringify(rows[0].j)
      if (json.includes('$mig$')) throw new Error('구분자 충돌: ' + t)
      await sql(NEW, `insert into public.${id(t)} ${identity[0].n ? 'overriding system value' : ''}
        select * from json_populate_recordset(null::public.${id(t)}, $mig$${json}$mig$::json);`)
    }
    console.log(`${t}: ${n}`)
  }
  await sql(NEW, `do $$ declare r record; begin
    for r in select c.relname tbl, a.attname col, pg_get_serial_sequence(format('public.%I', c.relname), a.attname) seq
      from pg_attribute a join pg_class c on c.oid = a.attrelid
      where c.relnamespace = 'public'::regnamespace and c.relname in (${inList}) and a.attnum > 0
        and pg_get_serial_sequence(format('public.%I', c.relname), a.attname) is not null
    loop
      execute format('select setval(%L, coalesce((select max(%I) from public.%I), 0) + 1, false)', r.seq, r.col, r.tbl);
    end loop; end $$;`)
  // owned by 가 없는 기본값 시퀀스도 최대값 이후로
  const defs = await sql(NEW, `select c.relname tbl, a.attname col,
      (regexp_match(pg_get_expr(d.adbin, d.adrelid), 'nextval\\(''(?:public\\.)?"?([^"'']+)"?''::regclass'))[1] seq
    from pg_attrdef d join pg_class c on c.oid = d.adrelid join pg_attribute a on a.attrelid = d.adrelid and a.attnum = d.adnum
    where c.relnamespace = 'public'::regnamespace and c.relname in (${inList}) and pg_get_expr(d.adbin, d.adrelid) like 'nextval%'`)
  for (const d of defs) {
    await sql(NEW, `select setval('public.${id(d.seq)}', coalesce((select max(${id(d.col)}) from public.${id(d.tbl)}), 0) + 1, false)`)
  }
  console.log('시퀀스 재설정 완료')
}

async function verify() {
  let ok = true
  for (const t of TABLES) {
    const q = `select count(*)::int n, md5(coalesce(string_agg(x::text, '|' order by x::text), '')) h from public.${id(t)} x`
    const [[a], [b]] = await Promise.all([sql(OLD, q), sql(NEW, q)])
    const same = a.n === b.n && a.h === b.h
    if (!same) ok = false
    console.log(`${same ? 'OK  ' : 'DIFF'} ${t}: ${a.n} → ${b.n}`)
  }
  console.log(ok ? '\n전체 일치' : '\n불일치 있음')
  process.exit(ok ? 0 : 1)
}

if (cmd === 'schema') await schema()
else if (cmd === 'data') await data()
else if (cmd === 'verify') await verify()
else console.log('schema | data | verify')
